### ISSUE TITLE
torrentgalaxy no longer works.

### ISSUE THREAD

**Issue by swannie-eire** [nindogo/qbtSearchScripts#12]
It imports fine to qbittorrent but does not find anything when searching for things that do exist.

I tired running the script itself with the dependencies and get the same result.

Currenlty running qBittorrent v4.3.2 Web UI (64-bit) as docker container from image ghcr.io/linuxserver/qbittorrent

**Comment by hdcTenBasePid** [comment]
It doesn't work because it returns nothing, _prettyprinter_ is never called..
The site format has changed.

I've modified the script so that it works. But there are areas of code that could probably be removed has they don't do anything. Mainly the _self.count_div_ var located throughout the script.
I added a new var _get_next_ and amended the class names to reflect the current site. I really only made 7 changes and 1 is just a placeholder for future error trapping, So here it is.

[torrentgalaxy.py.txt](https://github.com/nindogo/qbtSearchScripts/files/7529939/torrentgalaxy.py.txt)

Thanks for the different approach to other plugins used for qBittorrent, I enjoyed it.

**Comment by swannie-eire** [comment]
Thanks for the response. 

I use jackett now for searching sites so this can be closed.

**Comment by nindogo** [comment]
> The site format has changed.

Yoh @hdcTenBasePid - just seeing this. I have changed it but not with this. Sorry I have not been maintaining this properly.

**Comment by hdcTenBasePid** [comment]
Hey, thanks for the reply @nindogo.

Yes site layouts and back engines are changing more often these days.
Have fun!
